import Head from "next/head";
import styles from "../styles/Home.module.css";

function usernameVariableMassage() {
  // Environment variable massaging. Much of the logic borrowed from https://github.com/cassidoo/link-in-bio-template
  const username_to_idx = Object.entries(process.env).filter((key) =>
    key[0].startsWith("NEXT_DEVTO_USERNAME")
  );
  const username = username_to_idx[0][1];
  return username;
}

export async function getServerSideProps(context) {
  let username = usernameVariableMassage();
  let github_token = process.env.NEXT_GITHUB_TOKEN;
  let twitter_bearerToken = process.env.NEXT_TWITTER_BEARER_TOKEN;

  //Here we retrieve data from 3 different sources with one query, woven together in a StepZen layer accessible at
  const response = await fetch(
    "https://graphql1f.steprz.net/api/1fec739d90f6028c74a6f19855c34277/__graphql",

    {
      method: "POST",

      headers: {
        "Content-Type": "application/json",
      },

      body: JSON.stringify({
        query: `query MyQuery ($github_token: Secret! $twitter_bearerToken: Secret!, $username: String! ) {
          devto_getArticles(username: $username, top: 3) {
            title
            published_at
            user {
              github_details(github_token: $github_token) {
                pinnedItems(first: 3) {
                  nodes {
                    ... on Github_Repository {
                      id
                      name
                      description
                    
                    }
                  }
                }
              }
          
              twitter_details(
                twitter_bearerToken: $twitter_bearerToken
              ) {
                pinned_tweet(
                  twitter_bearerToken: $twitter_bearerToken
                ) {
                  text
                }
              }
              github_username
              username
              twitter_username
            }
          }
        } 
        `,
        variables: {
          github_token: github_token,
          twitter_bearerToken: twitter_bearerToken,
          username: username,
        },
      }),
    }
  );

  let data = await response.json();

  return { props: data };
}

export default function Home({ data }) {
  //page to render if tweet fetch goes awry
  if (data.devto_getArticles[0].user.twitter_details.pinned_tweet === null) {
    return (
      <div className={styles.container}>
        <Head>
          <title>StepZen Portfolio Site</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            {" "}
            {data.devto_getArticles[0].user.username}&#39;s custom portfolio
          </h1>

          <div className={styles.grid}>
            <a
              href={`https://dev.to/${data.devto_getArticles[0].user.username}`}
              className={styles.card}
            >
              <h2>Top 3 DEV.to articles &rarr;</h2>
              <p> - {data.devto_getArticles[0].title} </p>
              <p> - {data.devto_getArticles[1].title} </p>
              <p> - {data.devto_getArticles[2].title} </p>
            </a>

            <a
              href={`https://github.com/${data.devto_getArticles[0].user.github_username}`}
              passHref
              className={styles.card}
            >
              <h2>Top Pinned Github Repos &rarr;</h2>
              <p>
                Name:{" "}
                {
                  data.devto_getArticles[0].user.github_details.pinnedItems
                    .nodes[0].name
                }
                Description:{" "}
                {
                  data.devto_getArticles[0].user.github_details.pinnedItems
                    .nodes[0].description
                }{" "}
              </p>
              <p>
                {" "}
                Name:{" "}
                {
                  data.devto_getArticles[0].user.github_details.pinnedItems
                    .nodes[1].name
                }
              </p>
              <p>
                Description:{" "}
                {
                  data.devto_getArticles[0].user.github_details.pinnedItems
                    .nodes[1].description
                }
              </p>
            </a>

            <a
              href={`https://twitter.com/${data.devto_getArticles[0].user.twitter_username}`}
              className={styles.card}
            >
              <h2>Pinned Tweet &rarr;</h2>
              <p>No pinned tweet found, possible key error.</p>
            </a>
          </div>
          <p className={styles.sub_headline}>
            powered by <a href="https://stepzen.com/">StepZen</a> and{" "}
            <a href="https://www.netlify.com/">Netlify </a>
          </p>
        </main>

        <footer className={styles.footer}></footer>
      </div>
    );

    //page to render if github fetch goes awry
  } else if (
    data.devto_getArticles[0].user.github_details.pinnedItems.nodes[0].name ===
    null
  ) {
    return (
      <div className={styles.container}>
        <Head>
          <title>StepZen Portfolio Site</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            {" "}
            {data.devto_getArticles[0].user.username}&#39;s custom portfolio
          </h1>

          <div className={styles.grid}>
            <a
              href={`https://dev.to/${data.devto_getArticles[0].user.username}`}
              className={styles.card}
            >
              <h2>Top 3 DEV.to articles &rarr;</h2>
              <p> - {data.devto_getArticles[0].title} </p>
              <p> - {data.devto_getArticles[1].title} </p>
              <p> - {data.devto_getArticles[2].title} </p>
            </a>

            <a
              href={`https://github.com/${data.devto_getArticles[0].user.github_username}`}
              passHref
              className={styles.card}
            >
              <h2>Top Pinned Github Repos &rarr;</h2>
              <p>No pinned Github repos found. Possible key error.</p>
            </a>

            <a
              href={`https://twitter.com/${data.devto_getArticles[0].user.twitter_username}`}
              className={styles.card}
            >
              <h2>Pinned Tweet &rarr;</h2>
              <p>
                {" "}
                {
                  data.devto_getArticles[0].user.twitter_details.pinned_tweet
                    .text
                }
              </p>
            </a>
          </div>
          <p className={styles.sub_headline}>
            powered by <a href="https://stepzen.com/">StepZen</a> and{" "}
            <a href="https://www.netlify.com/">Netlify </a>
          </p>
        </main>

        <footer className={styles.footer}></footer>
      </div>
    );
  }

  //page to render if devto fetch goes awry
  if (data.devto_getArticles[0].user === undefined) {
    return <div>No devto user found under that name</div>;

    //page to render when things go well
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>StepZen Portfolio Site</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            {" "}
            {data.devto_getArticles[0].user.username}&#39;s custom portfolio
          </h1>

          <div className={styles.grid}>
            <a
              href={`https://dev.to/${data.devto_getArticles[0].user.username}`}
              className={styles.card}
            >
              <h2>Top 3 DEV.to articles &rarr;</h2>
              <p> - {data.devto_getArticles[0].title} </p>
              <p> - {data.devto_getArticles[1].title} </p>
              <p> - {data.devto_getArticles[2].title} </p>
            </a>

            <a
              href={`https://github.com/${data.devto_getArticles[0].user.github_username}`}
              passHref
              className={styles.card}
            >
              <h2>Top Pinned Github Repos &rarr;</h2>
              <p>
                Name:{" "}
                {
                  data.devto_getArticles[0].user.github_details.pinnedItems
                    .nodes[0].name
                }
                Description:{" "}
                {
                  data.devto_getArticles[0].user.github_details.pinnedItems
                    .nodes[0].description
                }{" "}
              </p>
              <p>
                {" "}
                Name:{" "}
                {
                  data.devto_getArticles[0].user.github_details.pinnedItems
                    .nodes[1].name
                }
              </p>
              <p>
                Description:{" "}
                {
                  data.devto_getArticles[0].user.github_details.pinnedItems
                    .nodes[1].description
                }
              </p>
            </a>

            <a
              href={`https://twitter.com/${data.devto_getArticles[0].user.twitter_username}`}
              className={styles.card}
            >
              <h2>Pinned Tweet &rarr;</h2>
              <p>
                {" "}
                {
                  data.devto_getArticles[0].user.twitter_details.pinned_tweet
                    .text
                }
              </p>
            </a>
          </div>
          <p className={styles.sub_headline}>
            powered by <a href="https://stepzen.com/">StepZen</a> and{" "}
            <a href="https://www.netlify.com/">Netlify </a>
          </p>
        </main>

        <footer className={styles.footer}></footer>
      </div>
    );
  }
}
